SELECT * FROM CUSTOMERS WHERE SALARY > 2000;

SELECT * FROM CUSTOMERS WHERE AGE > 24 AND SALARY >= 4500;

SELECT * FROM CUSTOMERS WHERE AGE > 24 OR SALARY >= 4500;

SELECT * FROM CUSTOMERS WHERE SALARY LIKE '200%';

SELECT * FROM CUSTOMERS
ORDER BY SALARY DESC
LIMIT 2;

SELECT DISTINCT SALARY FROM CUSTOMERS
ORDER  BY SALARY DESC;